name: Shellcheck

on:
  push:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run shellcheck
        uses: actions/shellcheck-action@v1
        with:
          shell: bash
          exclude: |
            vendor/

